'use client';

import React, { useRef, useEffect } from 'react';
import { ChartLineUp, Sparkle, TrendUp, Scales, Leaf } from '@phosphor-icons/react';
import { ChatMessage, SourceCitation } from '../../types';
import { MessageBubble } from './MessageBubble';

interface ChatWindowProps {
  messages: ChatMessage[];
  onSelectPrompt: (prompt: string) => void;
  onShowSources: (sources?: SourceCitation[]) => void;
}

const SAMPLE_PROMPTS = [
  {
    title: 'Financial Turnover',
    desc: 'What was the total turnover generated by Pick n Pay in FY23?',
    icon: <TrendUp size={18} color="var(--text-secondary)" weight="bold" />,
  },
  {
    title: 'Community & Food Security',
    desc: 'How many meals and hampers were distributed by FoodForward SA?',
    icon: <Scales size={18} color="var(--text-secondary)" weight="bold" />,
  },
  {
    title: 'ESG & Sustainability',
    desc: 'What are the company’s net zero carbon and recycling targets for 2025?',
    icon: <Leaf size={18} color="var(--text-secondary)" weight="bold" />,
  },
];

export const ChatWindow: React.FC<ChatWindowProps> = ({
  messages,
  onSelectPrompt,
  onShowSources,
}) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  if (messages.length === 0) {
    return (
      <div
        style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '24px',
          maxWidth: '780px',
          margin: '0 auto',
          width: '100%',
        }}
      >
        <div
          style={{
            width: '56px',
            height: '56px',
            borderRadius: '16px',
            backgroundColor: '#2f2f2f',
            border: 'none',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'var(--text-primary)',
            marginBottom: '16px',
          }}
        >
          <Sparkle size={28} weight="fill" />
        </div>

        <h2 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px' }}>
          FinQuery Corporate Intelligence
        </h2>
        <p
          style={{
            fontSize: '13px',
            color: 'var(--text-secondary)',
            textAlign: 'center',
            lineHeight: '1.6',
            marginBottom: '32px',
            maxWidth: '560px',
          }}
        >
          Query indexed corporate ESG reports, sustainability databooks, and financial statements with zero cloud leakage.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '14px', width: '100%' }}>
          {SAMPLE_PROMPTS.map((item, i) => (
            <div
              key={i}
              onClick={() => onSelectPrompt(item.desc)}
              style={{
                backgroundColor: '#171717',
                border: 'none',
                borderRadius: 'var(--radius-md)',
                padding: '16px',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = '#2f2f2f';
                e.currentTarget.style.transform = 'translateY(-2px)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = '#171717';
                e.currentTarget.style.transform = 'translateY(0)';
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                {item.icon}
                <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-primary)' }}>
                  {item.title}
                </span>
              </div>
              <p style={{ fontSize: '11px', color: 'var(--text-secondary)', lineHeight: '1.4' }}>
                {item.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div
      style={{
        flex: 1,
        overflowY: 'auto',
        padding: '24px 20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
      }}
    >
      {messages.map((msg) => (
        <MessageBubble key={msg.id} message={msg} onShowSources={onShowSources} />
      ))}
      <div ref={bottomRef} />
    </div>
  );
};
