import requests
import json
import sys
import os

try:
    from deepeval.test_case import LLMTestCase
    from deepeval.metrics import FaithfulnessMetric, AnswerRelevancyMetric
    from deepeval import evaluate
except ImportError:
    print("Error: deepeval is not installed.")
    print("Please install it by running: pip install deepeval")
    sys.exit(1)

# Ensure OPENAI_API_KEY is set for the evaluator
if "OPENAI_API_KEY" not in os.environ:
    print("WARNING: OPENAI_API_KEY environment variable is not set.")
    print("DeepEval requires an OpenAI API Key to act as the LLM Judge (e.g., using GPT-4).")
    print("Please set it: set OPENAI_API_KEY=your_key")
    print("Proceeding, but evaluation might fail if local custom LLM is not configured for DeepEval.")

API_URL = "http://localhost:5000/api/chat"

# Pick n Pay Evaluation Dataset
TEST_CASES = [
    {
        "input": "What is math theory?",
        "expected_output": "This information is not present in the local financial dataset."
    },
    {
        "input": "What was the total turnover generated by Pick n Pay in FY23?",
        "expected_output": "The total turnover generated by Pick n Pay in FY23 was 106,561.8 Rand Million."
    },
    {
        "input": "What is the number of entrepreneurs enrolled in Enterprise and Supplier Development programme in FY23?",
        "expected_output": "The number of entrepreneurs enrolled in the Enterprise and Supplier Development programme in FY23 is 198."
    }
]

def query_finquery_api(question):
    payload = {
        "question": question
    }
    
    try:
        # Note: The stream=True is needed if the endpoint streams. 
        # But we can capture the whole streamed response by reading lines.
        response = requests.post(API_URL, json=payload, stream=True)
        response.raise_for_status()
        
        full_text = ""
        # Read the chunks
        for chunk in response.iter_content(chunk_size=None, decode_unicode=True):
            if chunk:
                full_text += chunk
        
        return full_text
    except Exception as e:
        print(f"Error calling API for question '{question}': {e}")
        return ""

def main():
    print("Generating responses from local FinQuery API...")
    
    test_cases = []
    
    for case in TEST_CASES:
        print(f"\nQuery: {case['input']}")
        actual_output = query_finquery_api(case["input"])
        print(f"Actual Output: {actual_output}")
        
        # DeepEval requires context. In a real scenario, we'd modify the API to return the context chunks as well.
        # For Faithfulness, we simulate the expected context or just test Answer Relevancy first.
        # Since we don't have the context returned in the stream easily, we will pass a placeholder 
        # or we'll focus on Answer Relevancy and correctness against expected output.
        
        test_case = LLMTestCase(
            input=case["input"],
            actual_output=actual_output,
            expected_output=case["expected_output"],
            retrieval_context=["Pick n Pay generated 106 561.8 Rand Million turnover in FY23. 198 entrepreneurs were enrolled in the Enterprise and Supplier Development programme."] # Placeholder context
        )
        test_cases.append(test_case)

    # Define metrics
    # threshold=0.7 is 70% passing grade. The user wants 95% precision ideally.
    faithfulness = FaithfulnessMetric(threshold=0.95)
    answer_relevancy = AnswerRelevancyMetric(threshold=0.95)

    print("\n--- Running DeepEval Benchmarks ---")
    evaluate(test_cases, [faithfulness, answer_relevancy])
    
if __name__ == "__main__":
    main()
